#!/usr/bin/env python3
"""Regression tests for scripts/check_hygiene.py.

Pins the behaviours that a naive edit silently breaks:
  1. real violations are still CAUGHT (the scanner must not become a rubber stamp);
  2. every allowlisted placeholder is still ALLOWED (it must not cry wolf).

Context: the two in-repo copies of check_hygiene.py once diverged — the path
regex quantifier (`+` vs `*`) and the placeholder list (15 vs 26 entries) — so
identical content passed in one repo and failed CI in the other. The placeholder
cases below are generated by iterating the scanner's own PLACEHOLDER_TOKENS, so
deleting or renaming any single entry fails the suite. The violation cases are
hardcoded fragments (assembled at runtime so this file itself stays clean).

Run: python tests/test_check_hygiene.py
"""
import importlib.util
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPT = os.path.join(REPO_ROOT, "scripts", "check_hygiene.py")

USERS = "Users"
SLASH = "/"
BACKSLASH = "\\"


def load_scanner():
    spec = importlib.util.spec_from_file_location("check_hygiene", SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# Each entry must be flagged. Fragments keep this file from tripping the scanner.
CATCH_CASES = [
    ("real home path, upper drive", "C:" + BACKSLASH + USERS + BACKSLASH + "RealPerson" + BACKSLASH + "docs"),
    ("real home path, lower drive", "d:" + SLASH + "users" + SLASH + "SomeUser" + SLASH + "file.txt"),
    ("mixed slashes", "E:" + SLASH + USERS + BACKSLASH + "AnotherName"),
    ("github PAT", "ghp_" + "A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8"),
    ("aws access key", "AKIA" + "3J7KLMNOPQRSTUVWX"),
    ("slack token", "xoxb-" + "123456789012-abcdefghijklmnop"),
    ("openai key", "sk-proj-" + "abcdefghijklmnopqrstuvwxyz0123456789ABCDEF"),
    ("google api key", "AIza" + "SyD8fK2mN9pQ4rT7vW1xY6zB3cE5gH8jL0a"),
    ("telegram bot token", "123456789:" + "AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsawX"),
    ("private key block", "-----BEGIN RSA " + "PRIVATE KEY-----"),
]

# Path placeholders: appended after a drive+Users prefix, they must be allowed.
# Every entry in PLACEHOLDER_TOKENS is exercised — the skip set is empty on
# purpose: an earlier version skipped '…' and 'xxxx' as "secret markers", which
# left them uncovered, so deleting them from the allowlist went undetected.
def path_allow_cases(scanner):
    return [
        (f"path placeholder: {token}", "C:" + SLASH + USERS + SLASH + token + SLASH + "docs")
        for token in sorted(scanner.PLACEHOLDER_TOKENS)
    ]


# Snapshot of the allowlist. The cases above are generated FROM the scanner's own
# set, so deleting an entry would silently shrink the case list and go unnoticed —
# the snapshot breaks that circularity: any add/remove/rename must be a deliberate
# edit here too. (This is exactly how a 15-vs-26-entry divergence once slipped by.)
EXPECTED_PLACEHOLDER_TOKENS = frozenset({
    "name", "username", "user", "yourname", "your-name", "your_user", "myuser",
    "account", "default", "public", "xxx", "xxxx",
    "%username%", "%userprofile%", "$user", "wdagutilityaccount",
    "<user>", "<username>", "<user-name>", "<your-user>", "<your-username>",
    "<当前用户>", "<用户名>", "<使用者>", "<你的用户名>", "当前用户", "用户名",
    "...", "…", "<...>", "***",
})


# Secret-shaped documentation examples: must be allowed, never flagged.
SECRET_ALLOW_CASES = [
    ("PAT doc example", "ghp_" + "x" * 20),
    ("openai doc example", "sk-" + "x" * 40),
    ("aws doc example", "AKIA" + "X" * 16),
    ("slack doc example", "xoxb-" + "x" * 16),
    ("redaction marker", "«redacted:ghp_…»"),
    ("bracketed token", "<YOUR_TOKEN>"),
    ("ellipsis form", "ghp_..."),
]


def main():
    scanner = load_scanner()
    allow_cases = path_allow_cases(scanner) + SECRET_ALLOW_CASES
    failures = []

    # Break the circularity: the case list is generated from the scanner's set,
    # so compare the set itself against a hardcoded snapshot.
    if scanner.PLACEHOLDER_TOKENS != EXPECTED_PLACEHOLDER_TOKENS:
        missing = EXPECTED_PLACEHOLDER_TOKENS - scanner.PLACEHOLDER_TOKENS
        added = scanner.PLACEHOLDER_TOKENS - EXPECTED_PLACEHOLDER_TOKENS
        if missing:
            failures.append(f"allowlist entries REMOVED (would cause false positives): {sorted(missing)}")
        if added:
            failures.append(f"allowlist entries ADDED without updating the snapshot: {sorted(added)}")

    for label, sample in CATCH_CASES:
        violations, _ = scanner.scan_text("sample.md", sample)
        if not violations:
            failures.append(f"NOT CAUGHT (rubber stamp): {label} -> {sample!r}")

    for label, sample in allow_cases:
        violations, _ = scanner.scan_text("sample.md", sample)
        if violations:
            failures.append(f"FALSE POSITIVE (cries wolf): {label} -> {violations[0]}")

    # The bare-path case must NOT match at all (no identity to leak).
    if scanner.MACHINE_PATH_PATTERN.search("C:" + SLASH + USERS + SLASH + " "):
        failures.append("FALSE POSITIVE: bare path with no name matched the machine-path rule")

    if failures:
        print(f"❌ {len(failures)} failure(s):")
        for f in failures:
            print(f"  - {f}")
        return 1

    print(f"✅ check_hygiene regression: {len(CATCH_CASES) + len(allow_cases) + 2} cases passed "
          f"({len(CATCH_CASES)} violations caught, {len(allow_cases)} placeholders allowed, "
          f"1 bare-path non-match, 1 allowlist snapshot)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
