/**
 * Hermes Desktop Plugin: tg-channel-themes (@emoegg 频道精选 15 款沉浸主题合集)
 *
 * 移植自 Telegram 频道 @emoegg 第 12 号精选主题合集（已精简剔除刺眼日间亮色，保留高颜值暗黑与舒眼米色）：
 *
 * 【经典 IM 社交系列】
 * 1. qq-classic: QQ 经典 (Such QQ)
 * 2. wechat-dark: 微信夜间 1 (小而美 8.0 暗黑模式)
 * 3. wechatify-dark: 微信夜间 2 (WeChatify Dark OLED)
 * 4. wechat-dark3: 微信夜间 3 (夜间微信)
 *
 * 【动漫 / 极简风格系列】
 * 5. anime-designer: 动漫夜间 (Designer)
 * 6. cream-sepia: 米色日间 (米色舒眼护眼羊皮纸)
 *
 * 【极客 / 编程审美暗黑系列】
 * 7. brownie-dark: 酒红简洁 (Brownie)
 * 8. palenight: 紫色简洁 (Palenight Material)
 * 9. spacegrey: 黄色文字 (Spacegrey)
 * 10. puaro-grey: 淡灰简洁 (Puaro)
 * 11. forest-green: 暗绿文字 (Forest Green)
 * 12. dracula-mint: 蓝绿夜间 (Dracula Mint)
 * 13. amber-orange: 橙黄夜间 (Is So Elegant)
 * 14. neon-purple: 暗紫夜间 (Buifys)
 * 15. jotunheim-blue: 湛蓝夜间 (Jotunheim)
 *
 * 每一个主题均注册至 THEMES_AREA，并在 Ctrl+K 命令面板中支持一键极速切换。
 */

import { host, PALETTE_AREA, requestTheme, THEMES_AREA } from '@hermes/plugin-sdk'

const SANS = 'Inter, "PingFang SC", "Segoe UI Variable Text", "Microsoft YaHei", -apple-system, sans-serif'
const MONO = '"JetBrains Mono", "Cascadia Code", "Fira Code", Consolas, monospace'
const TYPOGRAPHY = { fontSans: SANS, fontMono: MONO }

// ==================== 19 款精选主题定义 ====================

const ALL_THEMES = [
  // --- 1. QQ 经典 (Such QQ) ---
  {
    name: 'qq-classic',
    label: 'QQ 经典 (Such QQ)',
    description: 'Classic Tencent QQ blue theme with sky-blue bubbles and clean white cards',
    colors: {
      background: '#f2f4f7',
      foreground: '#1f2329',
      card: '#ffffff',
      cardForeground: '#1f2329',
      muted: '#e8ebf0',
      mutedForeground: '#8a919e',
      popover: '#ffffff',
      popoverForeground: '#1f2329',
      primary: '#0099ff',
      primaryForeground: '#ffffff',
      secondary: '#e6f4ff',
      secondaryForeground: '#0077cc',
      accent: '#e6f4ff',
      accentForeground: '#0077cc',
      border: '#dce1e8',
      input: '#ffffff',
      ring: '#0099ff',
      midground: '#0099ff',
      composerRing: '#0099ff',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#ffffff',
      sidebarBorder: '#e5e8ec',
      userBubble: '#12b7f5',
      userBubbleBorder: '#0ea5e9',
    },
    darkColors: {
      background: '#18191c',
      foreground: '#e1e4ea',
      card: '#222429',
      cardForeground: '#e1e4ea',
      muted: '#1e2025',
      mutedForeground: '#7a8190',
      popover: '#222429',
      popoverForeground: '#e1e4ea',
      primary: '#12b7f5',
      primaryForeground: '#ffffff',
      secondary: '#1c2b38',
      secondaryForeground: '#38bdf8',
      accent: '#233647',
      accentForeground: '#38bdf8',
      border: '#282b32',
      input: '#1e2025',
      ring: '#12b7f5',
      midground: '#12b7f5',
      composerRing: 'rgba(18, 183, 245, 0.45)',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#131416',
      sidebarBorder: '#24262b',
      userBubble: '#007acc',
      userBubbleBorder: '#0099ff',
    },
    typography: TYPOGRAPHY,
  },

  // --- 2. 微信夜间 1 (小而美 8.0 暗黑模式) ---
  {
    name: 'wechat-dark',
    label: '微信夜间 1 (小而美暗黑)',
    description: 'Official WeChat 8.0 dark mode with matte dark grey surfaces and deep emerald accents',
    colors: {
      background: '#191919',
      foreground: '#e1e1e1',
      card: '#2c2c2c',
      cardForeground: '#e1e1e1',
      muted: '#222222',
      mutedForeground: '#777777',
      popover: '#2c2c2c',
      popoverForeground: '#e1e1e1',
      primary: '#28b461',
      primaryForeground: '#ffffff',
      secondary: '#1b3524',
      secondaryForeground: '#28b461',
      accent: '#243f2d',
      accentForeground: '#34d399',
      border: '#2e2e2e',
      input: '#222222',
      ring: '#28b461',
      midground: '#28b461',
      composerRing: 'rgba(40, 180, 97, 0.4)',
      destructive: '#fa5151',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#131313',
      sidebarBorder: '#262626',
      userBubble: '#28b461',
      userBubbleBorder: '#239b54',
    },
    typography: TYPOGRAPHY,
  },

  // --- 4. 微信夜间 2 (WeChatify Dark OLED) ---
  {
    name: 'wechatify-dark',
    label: '微信夜间 2 (WeChatify Dark OLED)',
    description: 'WeChatify pure-black OLED optimized theme with high-contrast emerald glow',
    colors: {
      background: '#0d0d0e',
      foreground: '#ececec',
      card: '#18181b',
      cardForeground: '#ececec',
      muted: '#141416',
      mutedForeground: '#71717a',
      popover: '#18181b',
      popoverForeground: '#ececec',
      primary: '#22c55e',
      primaryForeground: '#ffffff',
      secondary: '#14331d',
      secondaryForeground: '#4ade80',
      accent: '#1c3d25',
      accentForeground: '#86efac',
      border: '#222226',
      input: '#161618',
      ring: '#22c55e',
      midground: '#22c55e',
      composerRing: 'rgba(34, 197, 94, 0.45)',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#080809',
      sidebarBorder: '#1a1a1d',
      userBubble: '#1a6e38',
      userBubbleBorder: '#22c55e',
    },
    typography: TYPOGRAPHY,
  },

  // --- 5. 微信夜间 3 (夜间微信) ---
  {
    name: 'wechat-dark3',
    label: '微信夜间 3 (夜间微信经典)',
    description: 'Classic high-contrast WeChat dark theme with vivid green outgoing bubble',
    colors: {
      background: '#16181a',
      foreground: '#e6edf3',
      card: '#24272c',
      cardForeground: '#e6edf3',
      muted: '#1b1d22',
      mutedForeground: '#88909c',
      popover: '#24272c',
      popoverForeground: '#e6edf3',
      primary: '#2ea44f',
      primaryForeground: '#ffffff',
      secondary: '#1c3523',
      secondaryForeground: '#3fb950',
      accent: '#23442c',
      accentForeground: '#56d364',
      border: '#2c3038',
      input: '#1d2025',
      ring: '#2ea44f',
      midground: '#2ea44f',
      composerRing: 'rgba(46, 164, 79, 0.45)',
      destructive: '#f85149',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#101214',
      sidebarBorder: '#22252a',
      userBubble: '#2ba245',
      userBubbleBorder: '#238636',
    },
    typography: TYPOGRAPHY,
  },

  // --- 6. 动漫夜间 (Designer) ---
  {
    name: 'anime-designer',
    label: '动漫夜间 (Designer)',
    description: 'Designer anime dark theme with deep midnight violet canvas and neon purple accents',
    colors: {
      background: '#12131c',
      foreground: '#e0e2ec',
      card: '#1b1d2a',
      cardForeground: '#e0e2ec',
      muted: '#171824',
      mutedForeground: '#898c9e',
      popover: '#1b1d2a',
      popoverForeground: '#e0e2ec',
      primary: '#9333ea',
      primaryForeground: '#ffffff',
      secondary: '#2e1c45',
      secondaryForeground: '#c084fc',
      accent: '#3b2359',
      accentForeground: '#d8b4fe',
      border: '#282b3d',
      input: '#191b26',
      ring: '#9333ea',
      midground: '#9333ea',
      composerRing: 'rgba(147, 51, 234, 0.45)',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#0c0d14',
      sidebarBorder: '#202231',
      userBubble: '#5b21b6',
      userBubbleBorder: '#7c3aed',
    },
    typography: TYPOGRAPHY,
  },

  // --- 7. 米色日间 (米色舒眼) ---
  {
    name: 'cream-sepia',
    label: '米色日间 (米色舒眼)',
    description: 'Eye-care sepia cream parchment daytime theme with calm forest green accents',
    colors: {
      background: '#f8f4ec',
      foreground: '#38332b',
      card: '#ffffff',
      cardForeground: '#38332b',
      muted: '#eee8dc',
      mutedForeground: '#857c6e',
      popover: '#ffffff',
      popoverForeground: '#38332b',
      primary: '#4d7c0f',
      primaryForeground: '#ffffff',
      secondary: '#f2f8e9',
      secondaryForeground: '#3f6212',
      accent: '#ecfccb',
      accentForeground: '#365314',
      border: '#e4dcd0',
      input: '#ffffff',
      ring: '#65a30d',
      midground: '#65a30d',
      composerRing: '#65a30d',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#f1ebd8',
      sidebarBorder: '#dfd4be',
      userBubble: '#65a30d',
      userBubbleBorder: '#4d7c0f',
    },
    typography: TYPOGRAPHY,
  },

  // --- 11. 酒红简洁 (Brownie) ---
  {
    name: 'brownie-dark',
    label: '酒红简洁 (Brownie)',
    description: 'Brownie deep dark chocolate and wine-burgundy palette with rich warm tones',
    colors: {
      background: '#1a1416',
      foreground: '#e5dadb',
      card: '#241b1f',
      cardForeground: '#e5dadb',
      muted: '#1e1619',
      mutedForeground: '#8f777b',
      popover: '#241b1f',
      popoverForeground: '#e5dadb',
      primary: '#b91c1c',
      primaryForeground: '#ffffff',
      secondary: '#3b181d',
      secondaryForeground: '#f87171',
      accent: '#4c1d24',
      accentForeground: '#fca5a5',
      border: '#332328',
      input: '#20171a',
      ring: '#b91c1c',
      midground: '#b91c1c',
      composerRing: 'rgba(185, 28, 28, 0.45)',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#120d0f',
      sidebarBorder: '#2b1c21',
      userBubble: '#831843',
      userBubbleBorder: '#9d174d',
    },
    typography: TYPOGRAPHY,
  },

  // --- 12. 紫色简洁 (Palenight Material) ---
  {
    name: 'palenight',
    label: '紫色简洁 (Palenight)',
    description: 'Classic Material Palenight deep indigo-slate theme with soft cyan-violet glow',
    colors: {
      background: '#292d3e',
      foreground: '#bfc7d5',
      card: '#1f2233',
      cardForeground: '#bfc7d5',
      muted: '#242838',
      mutedForeground: '#676e95',
      popover: '#1f2233',
      popoverForeground: '#bfc7d5',
      primary: '#c792ea',
      primaryForeground: '#1e2029',
      secondary: '#363d59',
      secondaryForeground: '#c792ea',
      accent: '#3e4466',
      accentForeground: '#82aaff',
      border: '#383e5a',
      input: '#212435',
      ring: '#c792ea',
      midground: '#c792ea',
      composerRing: 'rgba(199, 146, 234, 0.45)',
      destructive: '#ff5370',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#1e2029',
      sidebarBorder: '#30344d',
      userBubble: '#7c4dff',
      userBubbleBorder: '#82aaff',
    },
    typography: TYPOGRAPHY,
  },

  // --- 13. 黄色文字 (Spacegrey) ---
  {
    name: 'spacegrey',
    label: '黄色文字 (Spacegrey)',
    description: 'Sublime Spacegrey dark matte grey theme with distinctive amber yellow highlights',
    colors: {
      background: '#20242c',
      foreground: '#c0c5ce',
      card: '#2b303c',
      cardForeground: '#c0c5ce',
      muted: '#252a34',
      mutedForeground: '#65737e',
      popover: '#2b303c',
      popoverForeground: '#c0c5ce',
      primary: '#ebcb8b',
      primaryForeground: '#1e222a',
      secondary: '#394050',
      secondaryForeground: '#ebcb8b',
      accent: '#434c5e',
      accentForeground: '#ebcb8b',
      border: '#343d4d',
      input: '#242933',
      ring: '#ebcb8b',
      midground: '#ebcb8b',
      composerRing: 'rgba(235, 203, 139, 0.45)',
      destructive: '#bf616a',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#1a1d24',
      sidebarBorder: '#2c3340',
      userBubble: '#3f4859',
      userBubbleBorder: '#ebcb8b',
    },
    typography: TYPOGRAPHY,
  },

  // --- 14. 淡灰简洁 (Puaro) ---
  {
    name: 'puaro-grey',
    label: '淡灰简洁 (Puaro)',
    description: 'Understated Morandi muted neutral grey palette for calm and distraction-free work',
    colors: {
      background: '#23252b',
      foreground: '#d5d8df',
      card: '#2b2e36',
      cardForeground: '#d5d8df',
      muted: '#262930',
      mutedForeground: '#7a808e',
      popover: '#2b2e36',
      popoverForeground: '#d5d8df',
      primary: '#94a3b8',
      primaryForeground: '#0f172a',
      secondary: '#343842',
      secondaryForeground: '#e2e8f0',
      accent: '#3c414d',
      accentForeground: '#f1f5f9',
      border: '#373b45',
      input: '#25272e',
      ring: '#94a3b8',
      midground: '#94a3b8',
      composerRing: 'rgba(148, 163, 184, 0.45)',
      destructive: '#f87171',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#1b1d22',
      sidebarBorder: '#2e313a',
      userBubble: '#3f4450',
      userBubbleBorder: '#64748b',
    },
    typography: TYPOGRAPHY,
  },

  // --- 15. 暗绿文字 (Forest Green) ---
  {
    name: 'forest-green',
    label: '暗绿文字 (Forest Green)',
    description: 'Deep forest pine night theme with fresh moss emerald highlights and organic mood',
    colors: {
      background: '#121a15',
      foreground: '#d3e2d7',
      card: '#1a2620',
      cardForeground: '#d3e2d7',
      muted: '#152019',
      mutedForeground: '#738e7b',
      popover: '#1a2620',
      popoverForeground: '#d3e2d7',
      primary: '#10b981',
      primaryForeground: '#062817',
      secondary: '#20392b',
      secondaryForeground: '#34d399',
      accent: '#274735',
      accentForeground: '#6ee7b7',
      border: '#283c31',
      input: '#15221b',
      ring: '#10b981',
      midground: '#10b981',
      composerRing: 'rgba(16, 185, 129, 0.45)',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#0d1410',
      sidebarBorder: '#1f3027',
      userBubble: '#065f46',
      userBubbleBorder: '#10b981',
    },
    typography: TYPOGRAPHY,
  },

  // --- 16. 蓝绿夜间 (Dracula Mint) ---
  {
    name: 'dracula-mint',
    label: '蓝绿夜间 (Dracula Mint)',
    description: 'Dracula vampire night palette meets electric refreshing mint green accents',
    colors: {
      background: '#21222c',
      foreground: '#f8f8f2',
      card: '#282a36',
      cardForeground: '#f8f8f2',
      muted: '#191a21',
      mutedForeground: '#6272a4',
      popover: '#282a36',
      popoverForeground: '#f8f8f2',
      primary: '#50fa7b',
      primaryForeground: '#1e2029',
      secondary: '#2a3b34',
      secondaryForeground: '#8be9fd',
      accent: '#33483f',
      accentForeground: '#50fa7b',
      border: '#383a48',
      input: '#1f2029',
      ring: '#50fa7b',
      midground: '#50fa7b',
      composerRing: 'rgba(80, 250, 123, 0.45)',
      destructive: '#ff5555',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#191a21',
      sidebarBorder: '#2e303d',
      userBubble: '#245943',
      userBubbleBorder: '#50fa7b',
    },
    typography: TYPOGRAPHY,
  },

  // --- 17. 橙黄夜间 (Is So Elegant) ---
  {
    name: 'amber-orange',
    label: '橙黄夜间 (Is So Elegant)',
    description: 'Warm glowing amber-gold and obsidian charcoal theme with rich evening contrast',
    colors: {
      background: '#191715',
      foreground: '#eae5dc',
      card: '#24201c',
      cardForeground: '#eae5dc',
      muted: '#1e1a17',
      mutedForeground: '#8e8477',
      popover: '#24201c',
      popoverForeground: '#eae5dc',
      primary: '#f59e0b',
      primaryForeground: '#1f1606',
      secondary: '#3b2a16',
      secondaryForeground: '#fbbf24',
      accent: '#4a351b',
      accentForeground: '#fcd34d',
      border: '#383028',
      input: '#1f1b18',
      ring: '#f59e0b',
      midground: '#f59e0b',
      composerRing: 'rgba(245, 158, 11, 0.45)',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#12100e',
      sidebarBorder: '#2d2720',
      userBubble: '#78350f',
      userBubbleBorder: '#f59e0b',
    },
    typography: TYPOGRAPHY,
  },

  // --- 18. 暗紫夜间 (Buifys) ---
  {
    name: 'neon-purple',
    label: '暗紫夜间 (Buifys)',
    description: 'Electric cyber violet night theme with saturated purple glow and deep midnight canvas',
    colors: {
      background: '#161320',
      foreground: '#e6e1f4',
      card: '#201c2e',
      cardForeground: '#e6e1f4',
      muted: '#1a1626',
      mutedForeground: '#7d7495',
      popover: '#201c2e',
      popoverForeground: '#e6e1f4',
      primary: '#a855f7',
      primaryForeground: '#ffffff',
      secondary: '#36224e',
      secondaryForeground: '#d8b4fe',
      accent: '#442a63',
      accentForeground: '#e9d5ff',
      border: '#2e2742',
      input: '#1c1829',
      ring: '#a855f7',
      midground: '#a855f7',
      composerRing: 'rgba(168, 85, 247, 0.45)',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#100e18',
      sidebarBorder: '#272138',
      userBubble: '#6b21a8',
      userBubbleBorder: '#a855f7',
    },
    typography: TYPOGRAPHY,
  },

  // --- 19. 湛蓝夜间 (Jotunheim) ---
  {
    name: 'jotunheim-blue',
    label: '湛蓝夜间 (Jotunheim)',
    description: 'Norse arctic deep ocean oceanic night theme with crystalline ice-blue neon glow',
    colors: {
      background: '#0d1522',
      foreground: '#e1e9f5',
      card: '#142032',
      cardForeground: '#e1e9f5',
      muted: '#101a2a',
      mutedForeground: '#6c7f99',
      popover: '#142032',
      popoverForeground: '#e1e9f5',
      primary: '#0284c7',
      primaryForeground: '#ffffff',
      secondary: '#18344f',
      secondaryForeground: '#38bdf8',
      accent: '#1e4063',
      accentForeground: '#7dd3fc',
      border: '#21334d',
      input: '#121c2d',
      ring: '#38bdf8',
      midground: '#38bdf8',
      composerRing: 'rgba(56, 189, 248, 0.45)',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      sidebarBackground: '#080d16',
      sidebarBorder: '#1c2b42',
      userBubble: '#0369a1',
      userBubbleBorder: '#38bdf8',
    },
    typography: TYPOGRAPHY,
  },
]

// ==================== 插件注册入口 ====================

export default {
  id: 'tg-channel-themes',
  name: 'Telegram Channel Themes (@emoegg 19-in-1)',
  register(ctx) {
    for (const item of ALL_THEMES) {
      // 1. 注册至 Hermes 核心主题池
      ctx.register({
        id: `theme-${item.name}`,
        area: THEMES_AREA,
        data: item,
      })

      // 2. 在 Ctrl+K 命令面板中注册快速切换指令
      ctx.register({
        id: `palette-switch-${item.name}`,
        area: PALETTE_AREA,
        data: {
          id: `theme.switch.${item.name}`,
          label: `Theme: 切换到 ${item.label}`,
          keywords: ['theme', 'tg', 'emoegg', item.name, item.label],
          run: () => {
            requestTheme(item.name)
            host.notify?.({
              kind: 'info',
              message: `🎨 已切换到「${item.label}」`,
            })
          },
        },
      })
    }
  },
}
